# Nom du site
title: AISI Cyber-Team
description: Cyber-Team Homepage

# URL du site (remplacez par votre URL GitHub Pages)

# Paramètres de Jekyll
theme: jekyll-theme-minimal  # Thème par défaut de Jekyll
markdown: kramdown  # Moteur de conversion Markdown

# Dossiers et fichiers à inclure/exclure
#include: [_pages]
#exclude: [README.md, LICENSE]

# Paramètres pour les articles de blog
permalink: /:year/:month/:day/:title/
