# Nom du site
title: AISI Cyber-Team
description: Cyber-Team Homepage

# URL du site (remplacez par votre URL GitHub Pages)

# Paramètres de Jekyll
#theme: minimal-jekyll  # Thème par défaut de Jekyll
remote_theme: alshedivat/al-folio@v0.15.0
plugins:
- jekyll-remote-theme
markdown: kramdown  # Moteur de conversion Markdown

# Dossiers et fichiers à inclure/exclure
#include: [_pages]
#exclude: [README.md, LICENSE]

# Paramètres pour les articles de blog
permalink: /:year/:month/:day/:title/
